# Generated by Django 5.2.8 on 2025-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('highlight_text', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('badge_text', models.CharField(blank=True, max_length=200, null=True)),
                ('search_placeholder', models.CharField(default='Search templates...', max_length=200)),
                ('image1', models.ImageField(upload_to='hero/')),
                ('image2', models.ImageField(upload_to='hero/')),
                ('image3', models.ImageField(upload_to='hero/')),
                ('image4', models.ImageField(upload_to='hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
