# Generated by Django 5.2.8 on 2025-11-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(help_text='FontAwesome or Heroicon class', max_length=50)),
                ('icon_bg', models.CharField(default='#4F46E5', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
