# Generated by Django 5.2.8 on 2025-11-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-code', 'Code'), ('fa-solid fa-cart-shopping', 'Ecommerce'), ('fa-solid fa-blog', 'Blog'), ('fa-solid fa-briefcase', 'Business'), ('fa-solid fa-camera', 'Camera'), ('fa-solid fa-bullhorn', 'Marketing'), ('fa-solid fa-mobile-screen-button', 'Mobile'), ('fa-solid fa-microchip', 'Technology'), ('fa-solid fa-store', 'Shop')], max_length=50),
        ),
    ]
