# Generated by Django 5.2.8 on 2025-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='featured_themes/')),
                ('preview_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-code', 'Code'), ('fa-solid fa-cart-shopping', 'Ecommerce'), ('fa-solid fa-blog', 'Blog'), ('fa-solid fa-briefcase', 'Business'), ('fa-solid fa-camera', 'Camera'), ('fa-solid fa-bullhorn', 'Marketing'), ('fa-solid fa-mobile-screen-button', 'Mobile'), ('fa-solid fa-stopwatch', 'Technology'), ('fa-solid fa-store', 'Shop')], max_length=50),
        ),
    ]
