# Generated by Django 5.2.8 on 2025-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_featuredtheme_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='showcase/')),
                ('item_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
