# Generated by Django 5.2.8 on 2025-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_showcasecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtheme',
            name='period',
            field=models.CharField(choices=[('week', 'This Week'), ('month', 'This Month')], default='week', max_length=10),
        ),
    ]
