# Generated by Django 5.2.8 on 2025-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_featuredtheme_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredtheme',
            name='period',
        ),
        migrations.AddField(
            model_name='featuredtheme',
            name='display',
            field=models.CharField(blank=True, choices=[('WEEK', 'This Week'), ('MONTH', 'This Month')], help_text='Where should this theme appear?', max_length=20, null=True),
        ),
    ]
