# Generated by Django 5.2.8 on 2025-11-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_featuredtheme_period_featuredtheme_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtheme',
            name='display',
            field=models.CharField(blank=True, choices=[('week', 'This Week'), ('week', 'This Month')], help_text='Where should this theme appear?', max_length=20, null=True),
        ),
    ]
