# Generated by Django 5.2.8 on 2025-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_featuredtheme_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtheme',
            name='category',
            field=models.CharField(blank=True, choices=[('business', 'Business Theme'), ('portfolio', 'Portfolio Theme'), ('blog', 'Blog Theme'), ('ecommerce', 'E-Commerce Theme')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='featuredtheme',
            name='collection',
            field=models.CharField(blank=True, choices=[('trending', 'Trending Collection'), ('new', 'New Arrivals'), ('bestseller', 'Bestseller')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='featuredtheme',
            name='template_type',
            field=models.CharField(blank=True, choices=[('html', 'HTML Templates'), ('landing', 'Landing Page Templates'), ('ui', 'UI Kits')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='featuredtheme',
            name='display',
            field=models.CharField(blank=True, choices=[('week', 'This Week'), ('month', 'This Month')], help_text='Where should this theme appear?', max_length=20, null=True),
        ),
    ]
