# Generated by Django 5.2.8 on 2025-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_whychooseus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseus',
            name='icon',
            field=models.CharField(choices=[('shield', 'Quality Guaranteed'), ('download', 'Instant Downloads'), ('headset', '24/7 Support'), ('refresh', 'Regular Updates'), ('award', 'Elite Authors'), ('dollar', 'Great Value')], help_text='Select icon for this feature', max_length=50),
        ),
    ]
