# Generated by Django 5.2.8 on 2025-11-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('shield', 'Quality Guaranteed'), ('download', 'Instant Downloads'), ('headset', '24/7 Support'), ('refresh', 'Regular Updates'), ('award', 'Elite Authors'), ('dollar', 'Great Value')], help_text='Select icon for this feature', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
