# Generated by Django 5.2.8 on 2025-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ui',
            name='icon',
            field=models.CharField(choices=[('users', 'Active Users'), ('chart-line', 'Downloads'), ('award', 'Products'), ('globe', 'Countries')], help_text='Select icon for this feature', max_length=50),
        ),
    ]
