# Generated by Django 5.2.8 on 2025-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_ui_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ui',
            options={},
        ),
        migrations.RemoveField(
            model_name='ui',
            name='order',
        ),
        migrations.AddField(
            model_name='ui',
            name='bg_color',
            field=models.CharField(default='#DFFFE3', help_text='Pick background color', max_length=20),
        ),
    ]
