# Generated by Django 5.2.8 on 2025-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_ui_options_remove_ui_order_ui_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bullseye', 'Our Mission'), ('eye', 'Our Vision'), ('gears', 'Our Impact')], help_text='Select icon for this feature', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('bg_color', models.CharField(default='#D8E9FF', help_text='Pick background color', max_length=20)),
            ],
        ),
    ]
