# Generated by Django 5.2.8 on 2025-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='text_color',
            field=models.CharField(default='#13157c', help_text='Pick text color', max_length=20),
        ),
        migrations.AddField(
            model_name='ui',
            name='text_color',
            field=models.CharField(default='#84CC16', help_text='Pick text color', max_length=20),
        ),
    ]
