# Generated by Django 5.2.8 on 2025-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_core_text_color_ui_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team/')),
                ('bg_color', models.CharField(default='#0A3574', help_text='Background color under the image', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Name/Designation text color', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
