# Generated by Django 5.2.8 on 2025-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('envelope', 'Email Icon'), ('phone', 'Phone Icon'), ('comment', 'Live Chat Icon')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('line1', models.CharField(blank=True, max_length=200, null=True)),
                ('line2', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
