# Generated by Django 5.2.8 on 2025-11-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_cart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.featuredtheme'),
        ),
    ]
