# Generated by Django 5.2.8 on 2025-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_cartitem_cart_alter_cartitem_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='bg_color',
            field=models.CharField(default='#DFFFE3', help_text='Pick background color', max_length=20),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='text_color',
            field=models.CharField(default='#84CC16', help_text='Pick text color', max_length=20),
        ),
    ]
